#include <algorithm>
#include <array>
#include <atomic>
#include <cmath>
#include <cstdint>
#include <iostream>
#include <mutex>
#include <numeric>
#include <thread>
#include <tuple>
#include <vector>

namespace {
constexpr int kRank = 6;
constexpr int kLabels = 5;
constexpr int kOrder = 13;
struct Term { int sign = 1; long double coefficient = 0.0L; std::array<long double,kLabels> lambda{}; };
struct Chamber { int support=0,parity=0; std::array<int,kLabels> signs{}; std::array<int,kLabels> powers{}; std::vector<int> active; std::vector<Term> terms; std::vector<int> negative,positive; };
struct Failure { int support=0,parity=0,residual=0; std::vector<int> variables; int negatives=0,positives=0; };
long double magnitude(const Term&t,const std::array<int,kLabels>&f){long double r=t.coefficient;for(int i=0;i<kLabels;++i)r*=std::pow(t.lambda[static_cast<std::size_t>(i)],static_cast<long double>(f[static_cast<std::size_t>(i)]));return r;}
bool ge(long double a,long double b){const long double tol=1.0e-12L*(1.0L+std::abs(a)+std::abs(b));return a+tol>=b;}
bool hall(const Chamber&c,const std::array<int,kLabels>&f,const std::vector<int>&vars){std::vector<long double>m;for(const Term&t:c.terms)m.push_back(magnitude(t,f));std::vector<std::uint16_t>e(c.negative.size(),0);for(std::size_t n=0;n<c.negative.size();++n){const Term&x=c.terms[static_cast<std::size_t>(c.negative[n])];for(std::size_t p=0;p<c.positive.size();++p){const Term&y=c.terms[static_cast<std::size_t>(c.positive[p])];bool ok=true;for(int v:vars)if(!ge(y.lambda[static_cast<std::size_t>(v)],x.lambda[static_cast<std::size_t>(v)])){ok=false;break;}if(ok)e[n]|=static_cast<std::uint16_t>(1U<<p);}}const std::uint64_t lim=std::uint64_t{1}<<c.negative.size();for(std::uint64_t s=1;s<lim;++s){long double d=0,cap=0;std::uint16_t nb=0;for(std::size_t n=0;n<c.negative.size();++n)if((s>>n)&1U){d+=m[static_cast<std::size_t>(c.negative[n])];nb|=e[n];}for(std::size_t p=0;p<c.positive.size();++p)if((nb>>p)&1U)cap+=m[static_cast<std::size_t>(c.positive[p])];if(!ge(cap,d))return false;}return true;}
Chamber make_chamber(int support,int parity,const std::array<long double,kRank>&w,const std::array<std::array<long double,kLabels>,kRank>&v){Chamber c;c.support=support;c.parity=parity;int code=support;for(int l=0;l<kLabels;++l){int d=code%3;code/=3;c.signs[static_cast<std::size_t>(l)]=d==0?0:(d==1?1:-1);if(d)c.active.push_back(l);}int mp=0;for(std::size_t i=0;i<c.active.size();++i){int l=c.active[i];bool odd=((parity>>i)&1)!=0;c.powers[static_cast<std::size_t>(l)]=odd?1:2;if(c.signs[static_cast<std::size_t>(l)]<0&&odd)mp^=1;}if(mp)return c;for(int i=0;i<kRank;++i)for(int j=i+1;j<kRank;++j){Term t;t.coefficient=2*w[static_cast<std::size_t>(i)]*w[static_cast<std::size_t>(j)];t.lambda.fill(1);bool zero=false;for(int l:c.active){long double b=v[static_cast<std::size_t>(i)][static_cast<std::size_t>(l)]+static_cast<long double>(c.signs[static_cast<std::size_t>(l)])*v[static_cast<std::size_t>(j)][static_cast<std::size_t>(l)];if(std::abs(b)<1.0e-17L){zero=true;break;}int q=c.powers[static_cast<std::size_t>(l)];if(b<0&&(q&1))t.sign=-t.sign;t.coefficient*=std::pow(std::abs(b),static_cast<long double>(q));t.lambda[static_cast<std::size_t>(l)]=b*b;}if(!zero)c.terms.push_back(t);}for(std::size_t i=0;i<c.terms.size();++i)(c.terms[i].sign<0?c.negative:c.positive).push_back(static_cast<int>(i));return c;}
bool separated(const Chamber&c){return c.signs==std::array<int,kLabels>{-1,0,0,0,-1}&&c.powers==std::array<int,kLabels>{1,0,0,0,1};}
}
int main(){const long double pi=acosl(-1);std::array<long double,kRank>w{};std::array<std::array<long double,kLabels>,kRank>v{};for(int n=0;n<kRank;++n){long double a=pi*static_cast<long double>(n+1)/kOrder;w[static_cast<std::size_t>(n)]=4*sinl(a)*sinl(a)/kOrder;for(int l=0;l<kLabels;++l)v[static_cast<std::size_t>(n)][static_cast<std::size_t>(l)]=sinl(static_cast<long double>(2*l+3)*a)/sinl(a);}std::atomic<int>next{0};std::mutex mu;std::vector<Failure>fails;std::uint64_t chambers=0,regimes=0,direct=0,sep=0,pointwise=0;auto worker=[&](){std::vector<Failure>lf;std::uint64_t lc=0,lr=0,ld=0,ls=0,lp=0;for(;;){int support=next.fetch_add(1);if(support>=243)break;int z=support,active=0,minus=0;for(int l=0;l<kLabels;++l){int d=z%3;z/=3;if(d){++active;if(d==2)++minus;}}if(!active||!minus)continue;for(int parity=0;parity<(1<<active);++parity){Chamber c=make_chamber(support,parity,w,v);if(c.terms.empty())continue;if(c.negative.empty()){int act=0;for(int l=0;l<kLabels;++l)if(c.signs[static_cast<std::size_t>(l)])++act;lp+=static_cast<std::uint64_t>(1<<act);continue;}int mp=0;for(int l:c.active)if(c.signs[static_cast<std::size_t>(l)]<0&&c.powers[static_cast<std::size_t>(l)]==1)mp^=1;if(mp)continue;++lc;int count=1<<active;if(separated(c)){ls+=static_cast<std::uint64_t>(count);continue;}for(int residual=0;residual<count;++residual){++lr;std::array<int,kLabels>f{};std::vector<int>vars;int i=0;for(int l=0;l<kLabels;++l)if(c.signs[static_cast<std::size_t>(l)]){if((residual>>i)&1){f[static_cast<std::size_t>(l)]=1;vars.push_back(l);}++i;}if(hall(c,f,vars))++ld;else lf.push_back({support,parity,residual,vars,static_cast<int>(c.negative.size()),static_cast<int>(c.positive.size())});}}}std::lock_guard<std::mutex>g(mu);chambers+=lc;regimes+=lr;direct+=ld;sep+=ls;pointwise+=lp;fails.insert(fails.end(),lf.begin(),lf.end());};std::vector<std::thread>pool;for(int i=0;i<5;++i)pool.emplace_back(worker);for(auto&t:pool)t.join();std::sort(fails.begin(),fails.end(),[](const Failure&a,const Failure&b){return std::tie(a.support,a.parity,a.residual)<std::tie(b.support,b.parity,b.residual);});std::cout<<"O11_DIRECT_CENSUS chambers="<<chambers<<" regimes="<<regimes<<" direct="<<direct<<" separated="<<sep<<" pointwise="<<pointwise<<" failures="<<fails.size()<<" threads=5\n";for(std::size_t i=0;i<std::min<std::size_t>(fails.size(),40U);++i){const auto&f=fails[i];std::cout<<"FAIL support="<<f.support<<" parity="<<f.parity<<" residual="<<f.residual<<" vars=";for(int x:f.variables)std::cout<<x+1<<',';std::cout<<" neg="<<f.negatives<<" pos="<<f.positives<<'\n';}}
