#!/usr/bin/env python3
"""n-copy analogue of scalar FM3 on SU(2)^n (Sp(2n) > Sp(2)^n):
<F, prod_{i<j} (chi1(x_i)-chi1(x_j))^{2r}> >= 0 for F in the cone generated by
S_p = sum_i V_p(x_i) and H_q = Sym^{q-1}(C^{2n}) restricted.  usage: probe_su2_fm3_ncopy.py n L N R"""
import sys, itertools
if len(sys.argv)<2 or sys.argv[1] in ('-h','--help'): print(__doc__); sys.exit(0)
n,L,N,R=map(int,sys.argv[1:5])
def cg(a,p): return range(abs(a-p),a+p+1,2)
def mul_single(F,i,p,s=1):
    out={}
    for k,v in F.items():
        for c in cg(k[i],p):
            kk=list(k); kk[i]=c; kk=tuple(kk); out[kk]=out.get(kk,0)+s*v
    return out
def add(A,B,s=1):
    C=dict(A)
    for k,v in B.items(): C[k]=C.get(k,0)+s*v
    return {k:v for k,v in C.items() if v}
def mulS(F,p):
    out={}
    for i in range(n): out=add(out,mul_single(F,i,p))
    return out
def compositions(t,k):
    if k==1: yield (t,); return
    for a in range(t+1):
        for rest in compositions(t-a,k-1): yield (a,)+rest
def mulH(F,q):
    out={}
    for comp in compositions(q-1,n):
        G=F
        for i,a in enumerate(comp):
            if a: G=mul_single(G,i,a)
        out=add(out,G)
    return out
def mulD(F,i,j):
    return add(mul_single(F,i,1),mul_single(F,j,1),-1)
zero=tuple([0]*n)
def weight_apply(F,r):
    for (i,j) in itertools.combinations(range(n),2):
        for _ in range(2*r): F=mulD(F,i,j)
    return F.get(zero,0)
gens=[('S%d'%p,p) for p in range(1,L+1)]+[('H%d'%q,q) for q in range(2,L+1)]
fails=0; tested=0; zeros=0
for cnt in range(0,N+1):
    for combo in itertools.combinations_with_replacement(range(len(gens)),cnt):
        F={zero:1}
        for gi in combo:
            name,lab=gens[gi]; F=mulS(F,lab) if name[0]=='S' else mulH(F,lab)
        for r in range(1,R+1):
            val=weight_apply(F,r); tested+=1
            if val==0: zeros+=1
            if val<0:
                fails+=1
                if fails<=12: print("FAIL n=%d r=%d F=%s value=%d"%(n,r,[gens[g][0] for g in combo],val),flush=True)
print("done n=%d L=%d N=%d R=%d tested=%d fails=%d zeros=%d"%(n,L,N,R,tested,fails,zeros),flush=True)
