#!/usr/bin/env python3
"""L1: quadrant walk monotonicity W_m((a+1,b-1)->(p,0)) >= W_m((a,b)->(p,0)).
L2: antidiagonal ballot dominance (ADB) of every F in the cone generated by S_p, H_q.
usage: probe_su2_fm_ballot_lemmas.py WMAX(L1 box) L N (L2 box)"""
import sys, itertools
if any(a in ('-h','--help') for a in sys.argv[1:]): print(__doc__); sys.exit(0)
WMAX, L, N = map(int, sys.argv[1:4])
# L1
from functools import lru_cache
@lru_cache(None)
def W(m,a,b,p):
    if a<0 or b<0: return 0
    if m==0: return 1 if (a==p and b==0) else 0
    return W(m-1,a+1,b,p)+W(m-1,a-1,b,p)+W(m-1,a,b+1,p)+W(m-1,a,b-1,p)
bad=0; tot=0
for m in range(WMAX+1):
    for n in range(1,WMAX+2):
        for b in range(1,n+1):
            a=n-b
            for p in range(0,n+m+1):
                tot+=1
                if W(m,a+1,b-1,p) < W(m,a,b,p):
                    bad+=1
                    if bad<=10: print("L1 FAIL m=%d (a,b)=(%d,%d) p=%d : %d < %d"%(m,a,b,p,W(m,a+1,b-1,p),W(m,a,b,p)))
print("L1 tested=%d fails=%d"%(tot,bad),flush=True)
# L2
def cg(a,p): return range(abs(a-p), a+p+1, 2)
def cmul(F,G):
    out={}
    for (a,b),u in F.items():
        for (c,d),v in G.items():
            for e in cg(a,c):
                for f in cg(b,d): out[(e,f)]=out.get((e,f),0)+u*v
    return {k:v for k,v in out.items() if v}
def adb(F):
    ns=set(a+b for (a,b) in F)
    for n in ns:
        s=0
        for b in range(0,n+1):
            s+=(-1)**b*F.get((n-b,b),0)
            if s<0: return (n,b,s)
    return None
gens=[('S%d'%p,{(p,0):1,(0,p):1}) for p in range(1,L+1)]+[('H%d'%q,{(a,q-1-a):1 for a in range(q)}) for q in range(2,L+1)]
bad=0; tot=0
for n in range(1,N+1):
    for combo in itertools.combinations_with_replacement(range(len(gens)),n):
        F={(0,0):1}
        for i in combo: F=cmul(F,gens[i][1])
        tot+=1
        r=adb(F)
        if r:
            bad+=1
            if bad<=10: print("L2 FAIL F=%s at antidiag n=%d b=%d partial=%d"%([gens[i][0] for i in combo],*r))
print("L2 tested=%d fails=%d"%(tot,bad),flush=True)
