#!/usr/bin/env python3
"""Test lambda-wise positivity: for F in the cone generated by S_p, H_q and each
partition lam of m, is column 0 of F * sch S_lam(C^{2|2}) a genuine SU(2) character (nonnegative coefficients)?
sch S_lam = (1/m!) sum_sigma chi^lam(sigma) prod_cycles (p_k(x) - p_k(y))."""
import sys, itertools, math
from fractions import Fraction
from functools import lru_cache
if any(a in ('-h','--help') for a in sys.argv[1:]):
    print("usage: probe_su2_fm_hookwise.py L N M  -- products of <=N generators S_p (p<=L), H_q (2<=q<=L); m<=M"); sys.exit(0)
L, N, M = map(int, sys.argv[1:4])

def partitions(n, maxp=None):
    if maxp is None: maxp = n
    if n == 0: yield (); return
    for k in range(min(n, maxp), 0, -1):
        for r in partitions(n-k, k): yield (k,)+r

# Murnaghan-Nakayama via beta-sets
def mn_char(lam, rho):
    @lru_cache(None)
    def rec(lam, i):
        if i == len(rho): return 1 if sum(lam) == 0 else 0
        k = rho[i]; n = len(lam)
        beta = [lam[j] + (n-1-j) for j in range(n)]
        tot = 0; bs = set(beta)
        for j, b in enumerate(beta):
            nb = b - k
            if nb < 0 or nb in bs: continue
            sign = (-1) ** sum(1 for c in beta if nb < c < b)
            newb = sorted([c for c in beta if c != b] + [nb], reverse=True)
            newlam = tuple(newb[t] - (n-1-t) for t in range(n))
            tot += sign * rec(newlam, i+1)
        return tot
    return rec(tuple(lam), 0)

def z_rho(rho):
    z = 1
    for k in set(rho):
        c = rho.count(k); z *= k**c * math.factorial(c)
    return z

# doubled Laurent polys: dict (i,j)->coef in z^i w^j
def lmul(A, B):
    C = {}
    for (a1,b1),c1 in A.items():
        for (a2,b2),c2 in B.items():
            k=(a1+a2,b1+b2); C[k]=C.get(k,0)+c1*c2
    return {k:v for k,v in C.items() if v}
def sch(lam):
    m = sum(lam); tot = {}
    for rho in partitions(m):
        ch = mn_char(lam, rho)
        if ch == 0: continue
        P = {(0,0):Fraction(1)}
        for k in rho:
            P = lmul(P, {(k,0):1,(-k,0):1,(0,k):-1,(0,-k):-1})
        w = Fraction(ch, z_rho(rho))
        for key,v in P.items(): tot[key]=tot.get(key,0)+w*v
    return {k:v for k,v in tot.items() if v}
def to_chars(P):
    # decompose W-invariant Laurent poly into chi_a(z) chi_b(w): coefficient of z^a w^b minus z^(a+2)... use dominant: mult = c(a,b)-c(a+2,b)-c(a,b+2)+c(a+2,b+2)
    D = {}
    for (i,j) in P:
        if i>=0 and j>=0:
            v = P.get((i,j),0)-P.get((i+2,j),0)-P.get((i,j+2),0)+P.get((i+2,j+2),0)
            if v: D[(i,j)] = v
    return D
def cg(a,p): return range(abs(a-p), a+p+1, 2)
def cmul(F, G):
    out = {}
    for (a,b),u in F.items():
        for (c,d),v in G.items():
            for e in cg(a,c):
                for f in cg(b,d):
                    out[(e,f)] = out.get((e,f),0)+u*v
    return {k:v for k,v in out.items() if v}
gens = [('S',p,{(p,0):1,(0,p):1} if p else {(0,0):2}) for p in range(1,L+1)]
gens += [('H',q,{(a,q-1-a):1 for a in range(q)}) for q in range(2,L+1)]
schs = {}
for m in range(1,M+1):
    for lam in partitions(m):
        if len(lam) > 2 and lam[2] > 2: continue  # outside (2|2) hook -> zero
        S = to_chars(sch(lam))
        if S: schs[lam] = S
print("hook modules:", {k: len(v) for k,v in schs.items()}, flush=True)
# sanity: sum f^lam sch_lam == D_1^m
fails = 0; tested = 0; worst = {}
for n in range(0, N+1):
    for combo in itertools.combinations_with_replacement(range(len(gens)), n):
        F = {(0,0):1}
        for i in combo: F = cmul(F, gens[i][2])
        for lam, S in schs.items():
            R = cmul(F, S); tested += 1
            col = {a:v for (a,b),v in R.items() if b == 0}
            neg = {a:v for a,v in col.items() if v < 0}
            if neg:
                fails += 1
                if fails <= 15:
                    print("FAIL lam=%s F=%s neg=%s" % (lam, [gens[i][0]+str(gens[i][1]) for i in combo], neg), flush=True)
print("done tested=%d fails=%d" % (tested, fails), flush=True)
