#!/usr/bin/env python3
"""GL(4)-Schur-wise test of scalar FM3: D_1^n = sum_lam f^lam s_lam(x,-y).
For F in the cone generated by S_p, H_q, test ell_lam(F)=sum_ab (-1)^b F_ab [S_lam C^4 : V_a x V_b] >= 0.
usage: probe_su2_fm3_gl4_twisted.py NDEG L N"""
import sys, itertools, sympy as sp
if len(sys.argv)<2 or sys.argv[1] in ('-h','--help'): print(__doc__); sys.exit(0)
NDEG,L,N=map(int,sys.argv[1:4])
z,w=sp.symbols('z w'); X=[z,1/z,w,1/w]
def schur4(lam):
    lam=list(lam)+[0]*(4-len(lam))
    num=sp.Matrix(4,4,lambda i,j: X[j]**(lam[i]+3-i)).det(); den=sp.Matrix(4,4,lambda i,j: X[j]**(3-i)).det()
    return sp.expand(sp.cancel(num/den))
def to_chars(expr):
    q=sp.expand(expr*(z-1/z)*(w-1/w)); P=sp.Poly(sp.expand(q*z**80*w**80),z,w)
    return {(i-81,j-81):int(c) for (i,j),c in P.terms() if i-80>=1 and j-80>=1}
def cg(a,p): return range(abs(a-p), a+p+1, 2)
def cmul(F,G):
    out={}
    for (a,b),u in F.items():
        for (c,d),v in G.items():
            for e in cg(a,c):
                for f in cg(b,d): out[(e,f)]=out.get((e,f),0)+u*v
    return {k:v for k,v in out.items() if v}
def parts(n,k=4,mx=None):
    if mx is None: mx=n
    if n==0: yield (); return
    if k==0: return
    for a in range(min(n,mx),0,-1):
        for r in parts(n-a,k-1,a): yield (a,)+r
lams=[(lam,to_chars(schur4(lam))) for n in range(2,NDEG+1,2) for lam in parts(n)]
gens=[('S%d'%p,{(p,0):1,(0,p):1}) for p in range(1,L+1)]+[('H%d'%q,{(a,q-1-a):1 for a in range(q)}) for q in range(2,L+1)]
fails={}
for n in range(0,N+1):
    for combo in itertools.combinations_with_replacement(range(len(gens)),n):
        F={(0,0):1}
        for i in combo: F=cmul(F,gens[i][1])
        for lam,C in lams:
            val=sum((-1)**b*F.get((a,b),0)*c for (a,b),c in C.items())
            if val<0:
                fails.setdefault(lam,[]).append(([gens[i][0] for i in combo],val))
for lam,C in lams:
    fl=fails.get(lam,[])
    print("lam=%-12s fails=%d %s"%(lam,len(fl),fl[:2]))
