#!/usr/bin/env python3
"""Exact audit of every load-bearing E8 negative-bound table row.

The expensive positive rectangular sums are regenerated by the OpenMP/GMP
checker.  This script independently replays the cheap exact-rational source,
pointwise-majorant, and moment-integral predicates that produced its negative
inputs.  Each nontrivial row runs in a fresh interpreter because the historical
certificate modules deliberately reuse mutable template parameters.
"""

from __future__ import annotations

import argparse
from fractions import Fraction
import importlib
import json
from pathlib import Path
import subprocess
import sys


EXPECTED_CELLS = {
    77: 57817,
    79: 68095,
    81: 79060,
    83: 91138,
    85: 103495,
    87: 116526,
    89: 130740,
    91: 69502,
    93: 53822,
    95: 29784,
    97: 35869,
    99: 42662,
    101: 49478,
    103: 56387,
    105: 63660,
    107: 70562,
    109: 77454,
    111: 84702,
    113: 91581,
    115: 98455,
    117: 111427,
    119: 15000,
    121: 74053,
    123: 28121,
    125: 8497,
    127: 10528,
    129: 12719,
    131: 17797,
    133: 13558,
}

COMPLEX_CASES = {
    77,
    79,
    81,
    83,
    85,
    87,
    89,
    91,
    93,
    95,
    97,
    99,
    101,
    103,
    105,
    107,
    109,
    111,
    113,
}


def require(checks: dict[str, bool]) -> dict[str, bool]:
    if not all(checks.values()):
        failed = [name for name, ok in checks.items() if not ok]
        raise RuntimeError("failed exact predicates: " + ", ".join(failed))
    return checks


def module(name: str):
    return importlib.import_module(name)


def audit_complex_case(n: int) -> tuple[Fraction, dict[str, bool]]:
    if n in {77, 79, 83, 87}:
        item = module(f"direct_chain_rect_e8_n{n}_certificate")
        item.configure()
        checks = {
            "moment_source": item.moment_source_check(),
            "negative_interval": item.template.optimized_negative_interval_check(),
            "positive_interval": item.template.optimized_positive_interval_check(),
            "moment_integral": item.optimized_negative_moment_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    if n == 81:
        item = module("direct_chain_rect_e8_n81_certificate")
        item.configure()
        checks = {
            "moment_source": item.moment_source_check(),
            "negative_interval": item.optimized_negative_subdivided_interval_check(),
            "positive_interval": item.template.optimized_positive_interval_check(),
            "moment_integral": item.optimized_negative_moment_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    if n == 85:
        item = module("direct_chain_rect_e8_n85_certificate")
        item.configure()
        checks = {
            "moment_source": item.moment_source_check(),
            "negative_interval": item.template.optimized_negative_interval_check(),
            "positive_interval": item.optimized_positive_subdivided_interval_check(),
            "moment_integral": item.optimized_negative_moment_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    if n in {89, 91}:
        item = module(f"direct_chain_rect_e8_n{n}_certificate")
        item.configure()
        checks = {
            "moment_source": item.moment_source_check(),
            "negative_interval": item.optimized_negative_interval_check(),
            "positive_interval": item.optimized_positive_interval_check(),
            "moment_integral": item.optimized_negative_moment_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    if n in {93, 95, 101}:
        item = module(f"direct_chain_rect_e8_n{n}_certificate")
        item.configure()
        checks = {
            "moment_source": item.moment_source_check(),
            "negative_interval": item.chebyshev_negative_interval_check(),
            "positive_interval": item.chebyshev_positive_interval_check(),
            "moment_integral": item.chebyshev_moment_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    if n == 103:
        item = module("direct_chain_rect_e8_n103_certificate")
        bernstein = module("direct_chain_rect_e8_n101_certificate")
        item.configure()
        helper = item.prev.helper
        factor = item.chebyshev_factor()
        x = [Fraction(0), Fraction(1)]
        x2 = helper.poly_mul(x, x)
        xp = helper.poly_pow(x, item.P_NEG)
        negative_factor = item.prev.compose_linear(
            factor, Fraction(-1), Fraction(0)
        )
        scale = Fraction(63, 65) * 16 ** (item.N - item.P_NEG)
        negative_lhs = helper.poly_scale(
            helper.poly_mul(
                helper.poly_mul(xp, helper.poly_add(x2, [Fraction(4)])),
                helper.poly_mul(negative_factor, negative_factor),
            ),
            scale,
        )
        negative_rhs = helper.poly_mul(
            helper.poly_pow(x, item.N), helper.poly_add(x2, [Fraction(-4)])
        )
        negative_quotient, negative_remainder = item.poly_divmod(
            helper.poly_add(negative_lhs, helper.poly_scale(negative_rhs, -1)),
            xp,
        )
        negative_reduced, endpoint_remainder = item.poly_divmod(
            negative_quotient, [Fraction(16), Fraction(-1)]
        )

        positive_lhs = helper.poly_scale(
            helper.poly_mul(
                helper.poly_mul(xp, helper.poly_add(x2, [Fraction(4)])),
                helper.poly_mul(factor, factor),
            ),
            scale,
        )
        positive_rhs = helper.poly_mul(
            helper.poly_pow(x, item.N),
            helper.poly_add([Fraction(4)], helper.poly_scale(x2, -1)),
        )
        positive_quotient, positive_remainder = item.poly_divmod(
            helper.poly_add(positive_lhs, helper.poly_scale(positive_rhs, -1)),
            xp,
        )
        checks = {
            "moment_source": item.moment_source_check(),
            "negative_division": not negative_remainder and not endpoint_remainder,
            "negative_interval_bernstein": bernstein.bernstein_positive_on(
                negative_reduced, Fraction(2), Fraction(16)
            ),
            "positive_division": not positive_remainder,
            "positive_interval_bernstein": bernstein.bernstein_positive_on(
                positive_quotient, Fraction(0), Fraction(2)
            ),
            "moment_integral": item.chebyshev_moment_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    if n in {97, 99}:
        item = module("direct_chain_rect_e8_n99_n97_certificate")
        checks = {
            "moment_source": item.moment_source_check(),
            "negative_interval": item.chebyshev_negative_interval_check(n),
            "positive_interval": item.chebyshev_positive_interval_check(n),
            "moment_integral": item.chebyshev_moment_check(),
        }
        return Fraction(item.negative_bound(n)), require(checks)

    if n == 105:
        item = module("direct_chain_rect_e8_n105_certificate")
        item.configure()
        checks = {
            "moment_source": item.helper.moment_source_check(),
            "negative_interval": item.chebyshev_negative_interval_check(),
            "positive_interval": item.chebyshev_positive_interval_check(),
            "moment_integral": item.chebyshev_moment_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    if n == 107:
        item = module("direct_chain_rect_e8_n107_certificate")
        item.configure()
        checks = {
            "moment_source": item.moment_source_check(),
            "negative_interval": item.asymmetric_negative_interval_check(),
            "positive_interval": item.asymmetric_positive_interval_check(),
            "moment_integral": item.asymmetric_moment_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    if n == 109:
        item = module("direct_chain_rect_e8_n109_certificate")
        item.configure()
        checks = {
            "moment_source": item.moment_source_check(),
            "moment_integral": item.high_moment_negative_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    if n == 111:
        item = module("direct_chain_rect_e8_n111_certificate")
        item.configure()
        checks = {
            "moment_source": item.base.low_moment_source_check(),
            "moment_integral": item.base.low_moment_negative_check(),
        }
        return Fraction(item.base.negative_bound()), require(checks)

    if n == 113:
        item = module("direct_chain_rect_e8_n113_certificate")
        checks = {
            "moment_source": item.low_moment_source_check(),
            "moment_integral": item.low_moment_negative_check(),
        }
        return Fraction(item.negative_bound()), require(checks)

    raise RuntimeError(f"unsupported complex E8 row n={n}")


def parse_table(path: Path) -> dict[int, tuple[int, Fraction]]:
    lines = path.read_text(errors="strict").splitlines()
    if not lines or lines[0] != "# label|n|expected_cells|negative_bound":
        raise RuntimeError("unexpected E8 negative-bound table header")
    rows: dict[int, tuple[int, Fraction]] = {}
    for line_number, line in enumerate(lines[1:], 2):
        if not line:
            continue
        parts = line.split("|")
        if len(parts) != 4:
            raise RuntimeError(f"malformed table row {line_number}")
        label, n_text, cells_text, bound_text = parts
        n = int(n_text)
        if label != f"n{n}" or n in rows:
            raise RuntimeError(f"bad or duplicate label at row {line_number}")
        bound = Fraction(bound_text)
        if bound <= 0:
            raise RuntimeError(f"nonpositive bound at row {line_number}")
        rows[n] = (int(cells_text), bound)
    if set(rows) != set(EXPECTED_CELLS):
        raise RuntimeError(
            f"E8 negative-bound row set changed: got={sorted(rows)}, "
            f"expected={sorted(EXPECTED_CELLS)}"
        )
    return rows


def worker(n: int) -> int:
    bound, checks = audit_complex_case(n)
    print(json.dumps({"n": n, "bound": str(bound), "checks": checks}, sort_keys=True))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--table",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "certificates/exceptional_rect/e8_rect_negative_bounds.tsv",
    )
    parser.add_argument("--worker", type=int, help=argparse.SUPPRESS)
    args = parser.parse_args()
    if args.worker is not None:
        if args.worker not in COMPLEX_CASES:
            parser.error("worker row is not a complex E8 negative-bound case")
        return worker(args.worker)

    rows = parse_table(args.table)
    for n, expected_cells in EXPECTED_CELLS.items():
        cells, table_bound = rows[n]
        if cells != expected_cells:
            raise RuntimeError(
                f"n={n}: table cell count {cells} != expected {expected_cells}"
            )
        if n in COMPLEX_CASES:
            result = subprocess.run(
                [sys.executable, str(Path(__file__).resolve()), "--worker", str(n)],
                cwd=Path(__file__).resolve().parent,
                check=True,
                text=True,
                capture_output=True,
            )
            payload = json.loads(result.stdout)
            source_bound = Fraction(payload["bound"])
            predicate_count = len(payload["checks"])
        else:
            source_bound = Fraction(2 * (16 * 16 + 4) * 16**n)
            predicate_count = 1
        if source_bound != table_bound:
            raise RuntimeError(
                f"n={n}: table bound does not match exact source calculation"
            )
        print(
            f"n={n} cells={cells} predicates={predicate_count} "
            "bound_match=OK"
        )

    print(f"E8_NEGATIVE_BOUND_TABLE_ROWS={len(rows)}")
    print("E8_NEGATIVE_BOUND_AUDIT: ALL PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
